excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - sociaBLETests
  - sociaBLEUITests
disabled_rules: # rule identifiers turned on by default to exclude from running
  - trailing_whitespace
